### ISSUE TITLE
Add the ability to create a user in a simple way

### ISSUE THREAD

**Issue by nils-van-zuijlen** [nils-van-zuijlen/arbre_competences#16]
Currently, if you want to create an user, you must go : 
1 - to the Profils creating page
2 - to create a new User for it
3 - to edit that user by adding its name and surname

We may create a page that condenses all this in ONE single location.

**Comment by Eragonfr** [comment]
This is a very good idea!

**Comment by Eragonfr** [comment]
Résolu avec le dernier commit sur `issue-16`

**Comment by nils-van-zuijlen** [comment]
The issue shouldn't be closed while pr ils still open
