### ISSUE TITLE
GitHub passe à Microsoft

### ISSUE THREAD

**Issue by Eragonfr** [nils-van-zuijlen/arbre_competences#42]
Suite au passage de GiHub à l'entreprise Microsoft j'ai décidé de fermer et détruire mes repos sur le site.
De plus je pense fermer mon compte GitHub, cela aura pour conséquence de bloquer mes participations à ce projet et à tous les projets sur GH.
Je demande donc une migration de ce dépôt vers un hébergement autre que GitHub(et de préférence pas GitLab.) un hébergement chez l'école démocratique peut-sans doute être envisagé ou l'hébergement sur une machine perso est une autre option.

**Comment by nils-van-zuijlen** [comment]
Arrète de déconner. C'est un comportement de kikou.
C'est pas parce que GH se fait racheter par MS que GH va changer.

**Comment by Eragonfr** [comment]
Oh si, tkt, ça va changer, et puis j'aime pas GH, gitea est mieux perso

**Comment by Eragonfr** [comment]
je garderais, perso que les trucs que je suis obligé d'avoir sur gh(le site de la paroisse et ce repo si on le migre pas)

**Comment by nils-van-zuijlen** [comment]
Reste jusqu'à ce que ça change. Tu risque de rester beaucoup plus longtemps que prévu.

**Comment by nils-van-zuijlen** [comment]
Ce repo ne migrera pas.

**Comment by Eragonfr** [comment]
dans ce cas je verais suivre un repo gitea et on verra

**Comment by Samuel29** [comment]
quel intérêt de changer d'hébergeur à part se prendre la tête?
Microsoft n'est pas Oracle, ils ne vont pas rendre tout payant
en tout cas tu as des alternatives + ou - "open":
framagit
gitlab
bitbucket
self-hosted (mais pas à l'école, pas accessible facilement)
